# Generated by Django 2.1.4 on 2018-12-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
